version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/Downloads/uploads:/app/resources  # 映射到 Mac 的 Downloads 目录
    environment:
      - PYTHONUNBUFFERED=1